[package]
name = "libp2p-bitswap"
version = "0.5.1"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
description = "Implementation of the ipfs bitswap protocol."
license = "MIT OR Apache-2.0"
repository = "https://github.com/ipfs-rust/libp2p-bitswap"

[build-dependencies]
prost-build = "0.6.1"

[dependencies]
async-std = { version = "1.6.2", features = ["attributes"] }
cid = "0.5.1"
fnv = "1.0.7"
futures = "0.3.5"
libp2p = { version = "0.22.0", default-features = false }
log = "0.4.11"
multihash = "0.2.0"
prost = "0.6.1"
thiserror = "1.0.20"
unsigned-varint = "0.4.0"

[dev-dependencies]
env_logger = "0.7.1"
libp2p = "0.22.0"

[patch.crates-io]
cid = { git = "https://github.com/dvc94ch/rust-cid", branch = "new-multihash" }
multihash = { git = "https://github.com/ipfs-rust/tiny-multihash" }
